In [2]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# 產出list

In [6]:
list(range(1,10,2)) #1-10取隔兩個

[1, 3, 5, 7, 9]

In [7]:
list("ABCDEF")

['A', 'B', 'C', 'D', 'E', 'F']

In [8]:
[x**2 for x in range(1,11)]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

# for迴圈

In [9]:
for i in range(1,6):
    print(i)

1
2
3
4
5


In [13]:
count=0
for i in range(1,101):
    count=count+i
print(count)

5050


# list.append

In [48]:
price=[120,1200,10000]
c=34.1415
L=[]

In [49]:
for p in price:
    tw=c*p
    print(tw)
    L.append(tw)
print(L)


4096.9800000000005
40969.8
341415.0
[4096.9800000000005, 40969.8, 341415.0]


In [3]:
L=[]    
L.append(input(">>"))
    

>>apple


# 字串分割

In [33]:
spam=input("Please enter the number")
P=[]
money=spam.split(" ")
for i in money:
    twd=float(i)*34.15
    P.append(int(twd))
print(P)

Please enter the number12 12 12 12 21
[409, 409, 409, 409, 717]


In [37]:
#如果不小心打太多空白怎麼辦咧
enter=input(">>")
L=enter.split()
print(L)

>>13 23         32 23
['13', '23', '32', '23']


In [38]:
p=[]
c=30.1123
def exchange(p):
    p=float(p)
    return p*c
    

In [43]:
#map(function,List)
L=[12,12,12]
list(map(exchange,L))

[361.3476, 361.3476, 361.3476]

In [44]:
def f(x):
    return x**2

In [45]:
f(2)

4

# lambda x:x*2

In [46]:
g=lambda x:x**2

In [49]:
g(3)

9

In [74]:
spam=input("Please enter the number")
mo=spam.split()
money=np.array(spam.split())
print(money)
#list(map(lambda y:y**2 , money)

Please enter the number12 12 12 
['12', '12', '12']
['12' '12' '12']


In [75]:
## egg=[9,4,8,7]
list(map(lambda x:x*2+1,egg))

[19, 9, 17, 15]

# list comprehension

In [76]:
L

[12, 12, 12]

In [ ]:
[float(p)]

# 合併list

In [88]:
L=[1,2,3,4,5]
S=[2,3,4]

In [89]:
p=L+S

# join

In [92]:
p.sort()
print(p)

[1, 2, 2, 3, 3, 4, 4, 5]


# 互動機器人

In [33]:
from ipywidgets import interact

In [34]:
def move(n=1):
    print(" "*n+"^_^"+" "*n+"^_^")

In [35]:
move()

 ^_^ ^_^


In [36]:
interact(move,n=(40))

interactive(children=(IntSlider(value=40, description='n', max=120, min=-40), Output()), _dom_classes=('widget…

<function __main__.move(n=1)>

In [34]:
for i in range(1,10):
    for j in range(1,10):
        for k in range(1,10):
            A[i][k]=1
print(A)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [12]:
A=np.zeros((10,10))
print(A)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
